### ISSUE TITLE
junit-lab argue

### ISSUE THREAD

**Issue by CharlotteE67** [cs304-spring2021/score-argue#1]
## student id
11812419

## is group project?
No, just weekly lab

## which part?
    junit-lab

## support material
我刚刚看了一下我好像不在某个队伍里，但是我这边有建junit仓库，有2个和我一起的contributers，也完成了lab的任务，不过不清楚这边team是怎么回事（有可能队长不小心解散了？），所以想问一下能不能argue到这个分数
![junit-lab仓库与contributers](https://user-images.githubusercontent.com/71111432/121151703-2efe1900-c877-11eb-8822-f9330a586ccd.png)

screenshots or github repo links
https://github.com/cs304-spring2021/junit-lab-xysy1
(repo links, but it's private so I'm not sure whether you can access it or not)

**Comment by stan6** [comment]
Ok will update
