### ISSUE TITLE
Final Project Argue

### ISSUE THREAD

**Issue by Juan-Chen45** [cs304-spring2021/score-argue#10]
## student id
11811810

## is group project?
Yes

## which part?
The timeline part.

## support material

![detailed_timeline](https://user-images.githubusercontent.com/65435431/121155857-c153ec00-c87a-11eb-9bb0-e3a711e665f1.png)

![version_history](https://user-images.githubusercontent.com/65435431/121155946-d92b7000-c87a-11eb-9fe0-70460adcfb8a.png)

The above is in our presentation slides and we have stated and explained our timeline and version history. But still 10 points are deducted from our scores.

screenshots or github repo links
[This link is to our final report presentation](https://github.com/cs304-spring2021/finalpre-debug-automaton)

**Comment by stan6** [comment]
The timeline deducted is because your group didn't implement 2 issue per person by the end of semester

**Comment by Juan-Chen45** [comment]
No actually we have, during the whole semester our group in total inplemented 8 issues and our group consists of 4 people.

**Comment by Juan-Chen45** [comment]
> The timeline deducted is because your group didn't implement 2 issue per person by the end of semester

No actually we have, during the whole semester our group in total inplemented 8 issues and our group consists of 4 people.

**Comment by stan6** [comment]
Can you give the name of the TA who graded your final presentation

**Comment by Juan-Chen45** [comment]
> Can you give the name of the TA who graded your final presentation

Of course, one of the TA is Hu Yubin. I don't know the other's name but I did my presentation at your lab class（Monday afternoon, International Class）. 

Also we are confused about the 2 points deducted for timeline and 2 points deducted for screenshot and explanation of important issues. These are all in our presentation slides and are all important components which hava their own title.

**Comment by stan6** [comment]
Ok. I think I know the problem. -2 were because the included timeline is only for week 14 and week 15 but the instruction asked for timeline for the entire semester. I will add back the 10 points since you have partial timeline but there is no version history. All screenshots were the pull requests itself.
