### ISSUE TITLE
ProjectProposal

### ISSUE THREAD

**Issue by zwebrain** [cs304-spring2021/score-argue#11]
## student id
11811721

## is group project?
Yes

## which part?
    * Proposal
    -2 because three teams choose this project, but we are earlier. And the score had been updated before, but it was changed back today...

## support material
    
<img width="316" alt="企业微信截图_16231394363453" src="https://user-images.githubusercontent.com/46642512/121162941-f6fbd380-c880-11eb-8a94-cd0df358ed27.png">
<img width="321" alt="企业微信截图_16231394441830" src="https://user-images.githubusercontent.com/46642512/121162997-00853b80-c881-11eb-84d5-a9f70bbb75d2.png">

**Comment by stan6** [comment]
Can you send the id of your group member and the link of project proposal

**Comment by zwebrain** [comment]
Group id: 4
Project proposal: https://github.com/cs304-spring2021/project-proposal-nolsp
Tencent document (145th edition): https://docs.qq.com/sheet/DWE94aEN2cWJWaHVn?tab=BB08J2

**Comment by stan6** [comment]
Ok. I have updated the score

**Comment by stan6** [comment]
Forget to mention that since the main change is to add only 2 point to project proposal,  some of you still have the same total score (after the division, didn't affect the total score).
