### ISSUE TITLE
Reclaim for Lab Scores

### ISSUE THREAD

**Issue by devinluo27** [cs304-spring2021/score-argue#12]
## student id
11813221

## is group project?
      NO.

## which part?
    * labs

## support material

Three of my Labs has not been judged, probably due to the change of my github username in the middle of the semester. I would highly appreciate it if you could have a look on my submissions attached below:

Metrics Lab: https://github.com/cs304-spring2021/metrics-lab-Aloofwisdom
Coverage Lab: https://github.com/cs304-spring2021/coverage-lab-Aloofwisdom
Reverse Engineering Lab: https://github.com/cs304-spring2021/reverseengineeringlab-Aloofwisdom

Thanks for you time and patience!

**Comment by stan6** [comment]
I replied to your email. Will update

**Comment by devinluo27** [comment]
> I replied to your email. Will update

Thanks in advance!
