### ISSUE TITLE
mp0 score argue

### ISSUE THREAD

**Issue by Chaoyism** [cs304-spring2021/score-argue#15]
## student id
11811014

## is group project?
No.

## which part?
    * mp0

## support material
Thanks for the chance to argue on the score!
When doing mp0, I was not sure how to describe the command to commit something to git. The tutorial asked without giving a definite commit message, so instead of using a message like "\"demo\"" after "-m", I wrote <message> to refer to any specific string. I also asked my lab tutor, Mr. Wang (Daxing), whether it was acceptable as an answer pointing to the screen, and got his approvement.
Therefore I hope I can get 10 instead of 9.5 in my mp0.
Thanks again!

My mp0 link:
https://github.com/cs304-spring2021/mp0-Chaoyi-1230/blob/master/README.md

**Comment by stan6** [comment]
The point deduction is because you don't have a valid git command so we deduct 0.5 from that. I checked, even after adding back 0.5, your total score still remain the same so there is no point arguing
