### ISSUE TITLE
mp1-part2-argue

### ISSUE THREAD

**Issue by Jiapeng-Pei** [cs304-spring2021/score-argue#17]
## student id
11810127

## is group project?
No
## which part?
    mp1-part2

## support material
评分细则里说我的screenshot corrupt，但是在我这边图片可以正常显示，我是把图片放到图床而没有上传到github，可能是网络问题导致图片无法显示而不是图片本身的问题。希望助教可以重新审阅一下这次lab。

screenshots or github repo links
![屏幕截图 2021-06-08 200533](https://user-images.githubusercontent.com/55074462/121181896-143a9d00-c895-11eb-9aac-d4b7da272de9.png)
![屏幕截图 2021-06-08 200609](https://user-images.githubusercontent.com/55074462/121181915-18ff5100-c895-11eb-838e-312fe8df4fdc.png)

https://github.com/cs304-spring2021/mp1-part2-Jiapeng-Pei
这里先放了两张截图，如果助教有需求我可以把截图上传到github上，保证正常显示

**Comment by Jiapeng-Pei** [comment]
而且我卡绩了，如果这一分算上的话对课程成绩帮助挺大的。
wish for your reply!

**Comment by stan6** [comment]
I saw the image clearly. Updated score
