### ISSUE TITLE
securitylab and ui-ci get 0

### ISSUE THREAD

**Issue by ChuXiyes** [cs304-spring2021/score-argue#18]
## student id
11812820

## is group project?
no

## which part?
    * securitylab 
    * ui-ci

## support material
the two part I got 0, and the comments are no README.md. But I have finished that two part.

screenshots or github repo links     
securitylab:  https://github.com/cs304-spring2021/securitylab-ChuXiyes    
ui-ci: https://github.com/cs304-spring2021/ui-ci-ChuXiyes

**Comment by stan6** [comment]
Wrong name. The correct name is README.md.  Please note that incorrectly named submission will not be graded.
