### ISSUE TITLE
对成绩册里显示没有readme.md的argue

### ISSUE THREAD

**Issue by AlpAcA0072** [cs304-spring2021/score-argue#2]
## student id
11812020

## is group project?
not group project

## which part?
    * lab exercise of metrics and coverage. 成绩册里显示没有readme.md

## support material
[coverage-lab](https://github.com/cs304-spring2021/coverage-lab-AlpAcA0072)

![image](https://user-images.githubusercontent.com/58430003/121152096-7f757680-c877-11eb-944f-c70caa9b8ea5.png)

[metrics-lab](https://github.com/cs304-spring2021/metrics-lab-AlpAcA0072)

![image](https://user-images.githubusercontent.com/58430003/121152129-84d2c100-c877-11eb-8366-a5ced194aadb.png)

screenshots or github repo links

**Comment by stan6** [comment]
README.md is not named correctly so you get zero.

**Comment by AlpAcA0072** [comment]
我这个也是可以在GitHub里正确显示的，也符合markdown的语法。如果不算readme的话github应该显示不出来的呀，希望能给个机会，谢谢老师!

**Comment by AlpAcA0072** [comment]
而且我认真的完成了，因为后缀扣掉整个练习的分数是不是太过严格了呀...

**Comment by stan6** [comment]
The instructions clearly stated the file name. We grade everyone the same way.
