### ISSUE TITLE
Argue on junit lab scores

### ISSUE THREAD

**Issue by XaviaXu** [cs304-spring2021/score-argue#3]
## student id
11811536

## is group project?
No

## which part?
lab assignment part

## support material
sakai gradebook:
![image](https://user-images.githubusercontent.com/71215499/121151921-5b199a00-c877-11eb-95c3-2db0eb3399db.png)

screenshot from my teammate:
![QQ图片20210608163453](https://user-images.githubusercontent.com/71215499/121152117-8308fd80-c877-11eb-8777-2527bdc9e89d.jpg)

link to github repo: 
https://github.com/cs304-spring2021/junit-lab-bugging

**Comment by stan6** [comment]
ok will update
