### ISSUE TITLE
JUnit-lab aruge

### ISSUE THREAD

**Issue by LightingTom** [cs304-spring2021/score-argue#4]
## student id
11813015

## is group project?
No, just weekly lab

## which part?
    JUnit_lab

## support material
这次lab我和队友以为只需要提交一份，于是只有他建了仓库，但是内容确实是我们一起完成的
![image](https://user-images.githubusercontent.com/59653302/121152788-18a48d00-c878-11eb-9f08-30bedaef5c90.png)
github repo link: https://github.com/cs304-spring2021/junit-lab-greatbryan
screenshots or github repo links

**Comment by stan6** [comment]
ok. will update
