### ISSUE TITLE
No readme.md argue

### ISSUE THREAD

**Issue by Bugjudger** [cs304-spring2021/score-argue#5]
## student id
11810121

## is group project?
not group project

## which part?
    *  lab exercise of securitylab and ui-ci. No readme.md
## support material
![image](https://user-images.githubusercontent.com/56737316/121153408-9ff20080-c878-11eb-9595-74eb3920e05c.png)

![image](https://user-images.githubusercontent.com/56737316/121153513-b5ffc100-c878-11eb-81b5-82760665043f.png)

screenshots or github repo links

**Comment by stan6** [comment]
Please send link of repo

**Comment by stan6** [comment]
Sorry. Your README.md is incorrectly named so we will not give any score for that
