### ISSUE TITLE
Junit lab argue

### ISSUE THREAD

**Issue by VG-Huai** [cs304-spring2021/score-argue#6]
## student id
11811311

## is group project?
No
## which part?
    * Weekly lab assignment

## support material
由于当时没有找到组员，单人建立了组完成了assignment，但是没有成绩。
[https://github.com/cs304-spring2021/junit-lab-deep_testing](url)
screenshots or github repo links
![junit_lab](https://user-images.githubusercontent.com/56375896/121153964-17c02b00-c879-11eb-800d-0aed24631fad.png)

**Comment by stan6** [comment]
ok. will update
