### ISSUE TITLE
JUnit-lab aruge

### ISSUE THREAD

**Issue by drumzhang** [cs304-spring2021/score-argue#7]
## student id
11811026

## is group project?
No, it is a lab

## which part?
    in lab4, JUnit_lab

## support material
您好，我和队友创了一个队伍然后一起做了这个lab，但是却得到了“not in any group”的回复，我现在也能看到我在我们队伍里面，请问这是怎么回事呢？谢谢！
仓库链接：https://github.com/orgs/cs304-spring2021/teams/se-lab4-test
截图：
![image](https://user-images.githubusercontent.com/51016630/121154697-c1072100-c879-11eb-85e0-d6664bcf70e5.png)
![image](https://user-images.githubusercontent.com/51016630/121154855-e136e000-c879-11eb-808e-248b546bc3bd.png)

**Comment by stan6** [comment]
ok will updated
