### ISSUE TITLE
Junit-Lab argue

### ISSUE THREAD

**Issue by nanfang-wuyu** [cs304-spring2021/score-argue#8]
## student id
11811512

## is group project?
No
## which part?
Junit-Lab

## support material
成绩回复一栏显示“not in any group”，但是我们是的确完成了这次lab作业的，以下是我们的repo link：
https://github.com/cs304-spring2021/junit-lab-se_junit_group
截图：
![G SI6`2PMI2}`M 3Z3~8Q}M](https://user-images.githubusercontent.com/60834053/121155838-bc8f3800-c87a-11eb-8fd5-c3a254d2002e.png)
![`AN{2PC165IDH2VAH (CJK1](https://user-images.githubusercontent.com/60834053/121155873-c618a000-c87a-11eb-8379-512a47e39619.png)

**Comment by stan6** [comment]
OK. I will update the score
